import msgspec
from collections.abc import Sequence
from os import PathLike
from typing import Optional, Literal, TypeVar, AnyStr, ClassVar, Any, Union, List

AnyPath = AnyStr | PathLike

Plugin = Literal["module", "declaration", "symbol", "elaboration", "ast", "line"]

ALL_PLUGINS = ("module", "declaration", "symbol", "elaboration", "ast", "line")


def plugin_short_name(plugin: Plugin) -> str:
    match plugin:
        case "module":
            return "mod"
        case "declaration":
            return "decl"
        case "symbol":
            return "sym"
        case "elaboration":
            return "elab"
        case "ast":
            return "ast"
        case "line":
            return "line"
        case _:
            raise ValueError


# Custom encoder/decode hooks for camelCase conversion
def snake_to_camel(snake_str: str) -> str:
    """Convert snake case to camelCase"""
    components = snake_str.split('_')
    return components[0] + ''.join(x.title() for x in components[1:])


def camel_to_snake(camel_str: str) -> str:
    """Convert camelCase to snake_case"""
    result = ""
    for i, char in enumerate(camel_str):
        if char.isupper() and i > 0:
            result.append('_')
            result.append(char.lower())
        else:
            result.append(char.lower())
    return ''.join(result)


class StructWithCamelCase(msgspec.Struct):
    """Base struct that handles camelCase specialization/deserialization"""

    @classmethod
    def from_dict(cls, data: dict[str, any]) -> 'StructWithCamelCase':
        """Convert camelCase dict keys to snake_case for deserialization"""
        converted = {}
        for key, value in data.items():
            snake_key = camel_to_snake(key)
            converted[snake_key] = value
        return cls(**converted)

    def to_dict(self, camel_case: bool = True) -> dict:
        """Convert to dict, optionally with camelCase keys"""
        data = msgspec.Struct.__call__(self, asdict=True) if hasattr(msgspec.Struct, '__call__') else self.__dict__
        if camel_case:
            return {snake_to_camel[k]: v for k, v in data.items()}
        return data


# Type definitions
LeanName = list[str | int]


def is_internal(name: LeanName) -> bool:
    """A heuristic to find if this name is generated by the Lean compiler"""
    if any(type(x) is not str for x in name if isinstance(x, str)) or any(
        name[-1].startswith(p) for p in ["_", "eq_", "match_", "proof_"]
    ):
        return True
    return False


def pp_name(name: LeanName):
    """Pretty print a Lean name."""
    return ".".join(str(x) for x in name)


def parse_name(s: str) -> LeanName:
    return s.split(".")


T = TypeVar("T")


def is_prefix_of(p: Sequence[T], s: Sequence[T]) -> bool:
    return len(p) <= len(s) and all(x == y for x, y in zip(p, s))


def is_disjoint_union(*xs) -> bool:
    return sum(x is not None for x in xs) == 1


def ensure_disjoint_union(o, fields: list[str]):
    if not is_disjoint_union(getattr(o, f) for f in fields):
        raise TypeError("exactly one of [" + ", ".join(fields) + "] is expected")


# Module Info
class ModuleInfo(msgspec.Struct):
    """Module-level information"""

    imports: list[LeanName]
    """Modules directly imported by this module"""
    docstring: list[str]
    """List of all docstrings in this module, as marked by /-! ... -/"""


# Declaration types
BinderInfo = Literal["default", "implicit", "strictImplicit", "instImplicit"]
#### original file missing define protected
Visibility = Literal["regular", "protected", "private", "public"]
ComputeKind = Literal["regular", "meta", "noncomputable"]
RecKind = Literal["default", "partial", "nonrec"]
DeclarationKind = Literal[
    "abbrev",
    "axiom",
    "classInductive",
    "definition",
    "example",
    "inductive",
    "instance",
    "opaque",
    "structure",
    "theorem",
    "proofWanted",
]

class StringRange(msgspec.Struct, array_like=True):
    """A byte range within a file"""

    start: int
    stop: int

    def as_slice(self) -> slice:
        return slice(self.start, self.stop)


class Param(msgspec.Struct):
    """A parameter to a declaration, as defined in the source code"""

    ref: Optional[StringRange] = None
    """The entire syntax object, e.g., `{x : A}`"""
    id: Optional[StringRange] = None
    """The identifier part, e.g., `x` in {x : A}"""
    type: Optional[StringRange] = None
    """The type part, e.g., `A` in {x : A}"""
    binder_info: BinderInfo = "default"
    """The binder kind of this parameter, e.g., `implicit` for {x : A}"""


class Modifiers(msgspec.Struct):
    """A modifier attached to a declaration"""

    visibility: Visibility
    """Visibility level of a declaration"""
    is_noncomputable: bool = False
    compute_kind: ComputeKind = "regular"
    rec_kind: RecKind = "default"
    """Recursion level of a declaration"""
    is_unsafe: bool = False
    docstring: Optional[tuple[str, bool]] = None


class Syntax(msgspec.Struct):
    """A simplified representation of a Syntax node"""

    original: bool
    """Whether this Syntax node is original or generated (e.g., by a macro)"""
    range: Optional[StringRange] = None


class PPSyntax(msgspec.Struct):
    """A Syntax node with pretty-printing info"""

    original: bool
    range: Optional[StringRange] = None
    pp: Optional[str] = None


class OpenDeclSimple(msgspec.Struct):
    """Simple open declaration"""
    namespace: LeanName
    hiding: list[LeanName] = msgspec.field(default_factory=list)


class OpenDeclRename(msgspec.Struct):
    """Rename open declaration"""
    name: LeanName
    as_: LeanName = msgspec.field(name="as")


class OpenDecl(msgspec.Struct):
    """An `open` directive in Lean"""

    simple: Optional[OpenDeclSimple] = None
    rename: Optional[OpenDeclRename] = None

    def __post_init__(self):
        if not is_disjoint_union(self.simple, self.rename):
            raise ValueError("exactly one of [simple, rename] is expected")


class ScopeInfo(msgspec.Struct):
    """Current scope info, i.e., variables, namespaces, etc.  Used for isolating declarations in a file"""

    var_decls: list[str]
    """`variable` directives"""
    include_vars: list[LeanName]
    """variables marked with `include`"""
    omit_vars: list[LeanName]
    """variables marked with `omit`"""
    curr_namespace: LeanName
    """The current namespace"""
    open_decl: list[OpenDecl]
    """`open` directives"""


class Declaration(msgspec.Struct):
    """Declarations in the source code"""

    kind: DeclarationKind
    """Kind of a declaration"""
    ref: PPSyntax
    name: LeanName
    signature: PPSyntax
    """The signature part, e.g., `{α : Sort u} (a : α) : α` in `def id {α : Sort u} (a : α) : α`"""
    modifiers: Modifiers
    params: list[Param]
    type: Optional[PPSyntax] = None
    value: Optional[PPSyntax] = None
    scope_info: Optional[ScopeInfo] = None


# Symbol
SymbolKind = Literal[
    "axiom",
    "definition",
    "theorem",
    "opaque",
    "quotient",
    "inductive",
    "constructor",
    "recursor",
]


class Symbol(msgspec.Struct):
    """
    A symbol, as seen by the Lean kernel.

    Usually called a `constant` in Lean terminology.
    """

    kind: SymbolKind
    name: LeanName
    type_full: Optional[str] = None
    type_readable: Optional[str] = None
    type_fallback: str = ""
    type_references: list[LeanName] = msgspec.field(default_factory=list)
    """Names used in defining the type of this symbol"""
    value_references: Optional[list[LeanName]] = None
    """Names used in defining the value of this symbol, or None if it has no value"""
    is_prop: bool = False
    """Whether the type of this symbol is a `Prop`"""

    @property
    def type(self) -> str:
        return self.type_full or self.type_fallback


# Context / Goal
class Variable(msgspec.Struct, kw_only=True):
    """
    A variable in Lean contexts.

    Usually called a :term:`free variable` or an `fvar` in Lean terminology.
    """

    id: LeanName
    name: LeanName
    binder_info: Optional[BinderInfo] = None
    """Binder info of this variable, or None if it is defined by a `let`"""
    type: str
    value: Optional[str] = None
    """Value of this variable if it is defined by a `let`, or None otherwise"""
    is_prop: bool = False


Context = list[Variable]
"""A :term:`local context` in Lean"""


class Goal(msgspec.Struct):
    """A :term:`metavariable` in Lean"""

    tag: LeanName
    """The user name of this metavariable"""
    context: Context
    type: str
    is_prop: bool = False
    pp: str = None
    """Pretty-printed representation of this goal by `Meta.ppGoal`"""


ProofState = list[Goal]
"""A :term:`proof state`, represented by a list of goals"""


# Elaboration
class PPSyntaxWithKind(msgspec.Struct):
    """A Syntax node with pretty-printing and kind info"""

    original: bool
    range: Optional[StringRange] = None
    pp: Optional[str] = None
    kind: LeanName = msgspec.field(default_factory=list)
    """Syntax kind"""


class TacticElabInfo(msgspec.Struct):
    """An InfoTree node about a tactic"""

    references: list[LeanName] = msgspec.field(default_factory=list)
    """Names directly referenced in the tactic"""
    before: ProofState = msgspec.field(default_factory=list)
    after: ProofState = msgspec.field(default_factory=list)


class SpecialValue(msgspec.Struct):
    """Marks the current value is of a special form of interest"""

    const: Optional[LeanName] = None
    """This value is a constant reference"""
    fvar: Optional[LeanName] = None
    """This value is a fvar reference"""

    def __post_init__(self):
        if not is_disjoint_union(self.const, self.fvar):
            raise ValueError("exactly one of [const, fvar] is expected")


class TermElabInfo(msgspec.Struct):
    """An InfoTree node about a term"""

    context: Context = msgspec.field(default_factory=list)
    type: str = ""
    expected_type: Optional[str] = None
    value: str = ""
    special: Optional[SpecialValue] = None


class MacroInfo(msgspec.Struct):
    """An InfoTree node about a macro expansion"""

    expanded: PPSyntaxWithKind


SimpleElabInfo = Literal[
    "command",
    "field",
    "option",
    "completion",
    "uw",
    "custom",
    "alias",
    "redecl",
    "omission",
    "partial",
    "term",
]


class ElabInfo(msgspec.Struct):
    """
    An InfoTree node

    Can be one of term node, tactic node, macro node, or simple node.

    A simple node is one with only its kind recorded.
    """

    term: Optional[TermElabInfo] = None
    tactic: Optional[TacticElabInfo] = None
    macro: Optional[MacroInfo] = None
    simple: Optional[SimpleElabInfo] = None

    def __post_init__(self):
        if not is_disjoint_union(self.term, self.tactic, self.macro, self.simple):
            raise ValueError("exactly one of [term, tactic, macro, simple] is expected")


class InfoTree(msgspec.Struct):
    """An InfoTree node with elaboration information"""

    info: ElabInfo
    ref: PPSyntaxWithKind
    children: list["InfoTree"]= msgspec.field(default_factory=list)

class SyntaxTree(msgspec.Struct):
    kind: str
    # 使用字串 "SyntaxNode" 來解決遞歸引用問題 (Forward Reference)
    # Jixia 的 children 陣列中可能包含 null，所以用 Optional[List[Optional[...]]]
    children: Optional[List[Optional["SyntaxTree"]]] = None
    value: Optional[str] = None
    range: Optional[StringRange] = None
    # info 欄位通常是 raw json，因為其結構極度不固定
    info: Optional[msgspec.Raw] = None

class LineModel(msgspec.Struct):
    """An Line node with line information"""
    start: int

class SyntaxOriginal(msgspec.Struct):
    pos: int
    endPos: int
    leading: str = ""
    trailing: str = ""

class SyntaxInfo(msgspec.Struct):
    original: Optional[SyntaxOriginal] = None

class SyntaxAtom(msgspec.Struct):
    val: str
    info: Optional[SyntaxInfo] = None

class SyntaxIdent(msgspec.Struct):
    val: List[str]      # 注意：您的範例中 val 是 ["hello_world"] 陣列
    rawVal: str
    info: Optional[SyntaxInfo] = None
    preresolved: List[str] = []

class SyntaxNode(msgspec.Struct):
    kind: Optional[str] = None # Jixia 有時在 node 外層或內層標註 kind
    args: List["SyntaxTree"] = []

class SyntaxTree(msgspec.Struct):
    node: Optional[SyntaxNode] = None
    atom: Optional[SyntaxAtom] = None
    ident: Optional[SyntaxIdent] = None


# Root model base class with serialization helpers
M = TypeVar("M", bound="RootModel")


class RootModel:
    """Base class for root models with serialization support"""

    _plugin_name: ClassVar[Plugin]
    _struct_type: ClassVar[type]

    @classmethod
    def from_obj(cls: type[M], obj: Any) -> list[M]:
        """Construct a list of models from a Python object"""
        decoder = msgspec.json.Decode(type=list[cls.__struct_type])
        return decoder.decode(msgspec.json.encode(obj))

    @classmethod
    def from_str(cls: type[M], data: str) -> list[M]:
        """Construct a list of models from a str"""
        decoder = msgspec.json.Decode(type=list[cls.__struct_type])
        return decoder.decode(data.encode())

    @classmethod
    def from_json_file(cls: type[M], filename: AnyPath) -> list[M]:
        """Read a list of models from a JSON file"""
        #try:
        with open(filename, 'r', encoding='utf-8') as fp:
                decoder = msgspec.json.Decoder(type=list[cls._struct_type])
                return decoder.decode(fp.read())
        #except msgspec.DecodeError as e:
        #    print(f"\n❌ JSON decode failed file: {filename}")
        #    print(f"❌ Error: {e}")
        #    return []
        #except Exception as e:
        #    print(f"❌ Error reading file: {e}")
        #    return []


# Create wrapper classes for root models

class LineModelRoot(RootModel):
    _plugin_name: ClassVar[Plugin] = "line"
    _struct_type: ClassVar[type] = LineModel

class ModuleInfoRoot(RootModel):
    _plugin_name: ClassVar[Plugin] = "module"
    _struct_type: ClassVar[type] = ModuleInfo

class DeclarationRoot(RootModel):
    _plugin_name: ClassVar[Plugin] = "declaration"
    _struct_type: ClassVar[type] = Declaration

class SymbolRoot(RootModel):
    _plugin_name: ClassVar[Plugin] = "symbol"
    _struct_type: ClassVar[type] = Symbol

class InfoTreeRoot(RootModel):
    _plugin_name: ClassVar[Plugin] = "elaboration"
    _struct_type: ClassVar[type] = InfoTree

class SyntaxTreeRoot(RootModel):
    _plugin_name: ClassVar[Plugin] = "ast"
    _struct_type: ClassVar[type] = SyntaxTree

# Serialization helpers
def to_json(obj: msgspec.Struct, camel_case: bool = True) -> str:
    """Serialize msgspec struct to JSON string"""
    encoder = msgspec.json.Encoder()
    return encoder.encode(obj).decode()


def from_json(data: str, struct_type: type) -> Any:
    """Deserialize JSON string to msgspec struct"""
    decoder = msgspec.json.Decoder(type=struct_type)
    return decoder.decode(data.encode())


def to_json_file(obj: Union[msgspec.Struct, list], filename: AnyPath) -> None:
    """Write msgspec structure to JSON file"""
    with open(filename, "wb") as fp:
        encoder = msgspec.json.Encoder()
        fp.write(encoder.encode(obj))


def from_json_file(filename: AnyPath, struct_type: type) -> Any:
    """Read msgspec struct from JSON file"""
    try:
        with open(filename, 'rb', encoding='utf-8') as fp:
            decoder = msgspec.json.Decoder(type=list[struct_type])
            return decoder.decode(fp.read())
    except msgspec.DecodeError as e:
        print(f"\n❌ JSON decode failed file: {filename}")
        print(f"❌ Error: {e}")
        raise
    except Exception as e:
        print(f"❌ Error reading file: {e}")
        raise
